const callingCodes=[
  { country: "Afghanistan", value: "93", code: "AF", phLength: 9 },
  { country: "Albania", value: "355", code: "AL",phLength:8 },
  { country: "Algeria", value: "213", code: "DZ", phLength: 9 },
  { country: "American Samoa", value: "1-684", code: "AS", phLength: 10 },
  { country: "Andorra", value: "376", code: "AD",phLength:6 },
  { country: "Angola", value: "244", code: "AO",phLength:9 },
  { country: "Anguilla", value: "1-264", code: "AI", phLength: 10 },
  { country: "Antarctica", value: "672", code: "AQ",phLength:6 },
  { country: "Antigua and Barbuda", value: "1-268", code: "AG", phLength: 10 },
  { country: "Argentina", value: "54", code: "AR",phLength:10 },
  { country: "Armenia", value: "374", code: "AM", phLength: 8 },
  { country: "Aruba", value: "297", code: "AW", phLength: 7 },
  { country: "Australia", value: "61", code: "AU", phLength: 9 },
  { country: "Austria", value: "43", code: "AT", phLength: 10 },
  { country: "Azerbaijan", value: "994", code: "AZ", phLength: 9 },
  { country: "Bahamas", value: "1-242", code: "BS", phLength: 10 },
  { country: "Bahrain", value: "973", code: "BH", phLength: 8 },
  { country: "Bangladesh", value: "880", code: "BD", phLength: 10 },
  { country: "Barbados", value: "1-246", code: "BB", phLength: 10 },
  { country: "Belarus", value: "375", code: "BY", phLength: 9 },
  { country: "Belgium", value: "32", code: "BE", phLength: 9 },
  { country: "Belize", value: "501", code: "BZ", phLength: 7 },
  { country: "Benin", value: "229", code: "BJ", phLength: 9 },
  { country: "Bermuda", value: "1-441", code: "BM", phLength: 10 },
  { country: "Bhutan", value: "975", code: "BT",phLength:8 },
  { country: "Bolivia", value: "591", code: "BO",phLength:8 },
  { country: "Bosnia and Herzegovina", value: "387", code: "BA", phLength: 8 },
  { country: "Botswana", value: "267", code: "BW" ,phLength:7},
  { country: "Brazil", value: "55", code: "BR", phLength: 11 },
  { country: "British Indian Ocean Territory", value: "246", code: "IO" },
  {
    country: "British Virgin Islands",
    value: "1-284",
    code: "VG",
    phLength: 10,
  },
  { country: "Brunei", value: "673", code: "BN",phLength:7 },
  { country: "Bulgaria", value: "359", code: "BG",phLength:9 },
  { country: "Burkina Faso", value: "226", code: "BF", phLength: 8 },
  { country: "Burundi", value: "257", code: "BI" },
  { country: "Cambodia", value: "855", code: "KH", phLength: 9 },
  { country: "Cameroon", value: "237", code: "CM", phLength: 9 },
  { country: "Canada", value: "1", code: "CA", phLength: 10 },
  { country: "Cape Verde", value: "238", code: "CV" },
  { country: "Cayman Islands", value: "1-345", code: "KY", phLength: 10 },
  { country: "Central African Republic", value: "236", code: "CF" },
  { country: "Chad", value: "235", code: "TD", phLength: 8 },
  { country: "Chile", value: "56", code: "CL", phLength: 9 },
  { country: "China", value: "86", code: "CN", phLength: 11 },
  { country: "Christmas Island", value: "61", code: "CX" },
  { country: "Cocos Islands", value: "61", code: "CC" },
  { country: "Colombia", value: "57", code: "CO", phLength: 10 },
  { country: "Comoros", value: "269", code: "KM" },
  { country: "Cook Islands", value: "682", code: "CK", phLength: 5 },
  { country: "Costa Rica", value: "506", code: "CR", phLength: 8 },
  { country: "Croatia", value: "385", code: "HR", phLength: 9 },
  { country: "Cuba", value: "53", code: "CU",phLength:8 },
  { country: "Curacao", value: "599", code: "CW" },
  { country: "Cyprus", value: "357", code: "CY", phLength: 8 },
  { country: "Czech Republic", value: "420", code: "CZ", phLength: 9 },
  { country: "Democratic Republic of the Congo", value: "243", code: "CD" },
  { country: "Denmark", value: "45", code: "DK", phLength: 8 },
  { country: "Djibouti", value: "253", code: "DJ" },
  { country: "Dominica", value: "1-767", code: "DM", phLength: 10 },
  { country: "Dominican Republic", value: "1-809", code: "DO",phLength:10 },
  { country: "East Timor", value: "670", code: "TL" },
  { country: "Ecuador", value: "593", code: "EC", phLength: 9 },
  { country: "Egypt", value: "20", code: "EG", phLength: 10 },
  { country: "El Salvador", value: "503", code: "SV", phLength: 8 },
  { country: "Equatorial Guinea", value: "240", code: "GQ" },
  { country: "Eritrea", value: "291", code: "ER" },
  { country: "Estonia", value: "372", code: "EE", phLength: 8 },
  { country: "Ethiopia", value: "251", code: "ET",phLength:10 },
  { country: "Falkland Islands", value: "500", code: "FK" },
  { country: "Faroe Islands", value: "298", code: "FO", phLength: 5 },
  { country: "Fiji", value: "679", code: "FJ",phLength:7 },
  { country: "Finland", value: "358", code: "FI",phLength:7 },
  { country: "France", value: "33", code: "FR",phLength:10 },
  { country: "French Polynesia", value: "689", code: "PF", phLength: 6 },
  { country: "Gabon", value: "241", code: "GA", phLength: 7 },
  { country: "Gambia", value: "220", code: "GM",phLength:7 },
  { country: "Georgia", value: "995", code: "GE", phLength: 9 },
  { country: "Germany", value: "49", code: "DE", phLength: 9 },
  { country: "Ghana", value: "233", code: "GH", phLength: 10 },
  { country: "Gibraltar", value: "350", code: "GI",phLength:8 },
  { country: "Greece", value: "30", code: "GR", phLength: 10 },
  { country: "Greenland", value: "299", code: "GL", phLength: 6 },
  { country: "Grenada", value: "1-473", code: "GD", phLength: 10 },
  { country: "Guam", value: "1-671", code: "GU", phLength: 10 },
  { country: "Guatemala", value: "502", code: "GT", phLength: 8 },
  { country: "Guernsey", value: "44-1481", code: "GG", phLength: 10 },
  { country: "Guinea", value: "224", code: "GN",phLength:9 },
  { country: "Guinea-Bissau", value: "245", code: "GW" },
  { country: "Guyana", value: "592", code: "GY",phLength:7 },
  { country: "Haiti", value: "509", code: "HT",phLength:8 },
  { country: "Honduras", value: "504", code: "HN", phLength: 8 },
  { country: "Hong Kong", value: "852", code: "HK", phLength: 8 },
  { country: "Hungary", value: "36", code: "HU", phLength: 9 },
  { country: "Iceland", value: "354", code: "IS",phLength:7 },
  { country: "India", value: "91", code: "IN", phLength: 10 },
  { country: "Indonesia", value: "62", code: "ID", phLength: 9 },
  { country: "Iran", value: "98", code: "IR", phLength: 10 },
  { country: "Iraq", value: "964", code: "IQ",phLength:10 },
  { country: "Ireland", value: "353", code: "IE", phLength: 9 },
  { country: "Isle of Man", value: "44-1624", code: "IM", phLength: 10 },
  { country: "Israel", value: "972", code: "IL", phLength: 9 },
  { country: "Italy", value: "39", code: "IT", phLength: 10 },
  { country: "Ivory Coast", value: "225", code: "CI" },
  { country: "Jamaica", value: "1-876", code: "JM", phLength: 10 },
  { country: "Japan", value: "81", code: "JP", phLength: 10 },
  { country: "Jersey", value: "44-1534", code: "JE" },
  { country: "Jordan", value: "962", code: "JO", phLength: 9 },
  { country: "Kazakhstan", value: "7", code: "KZ", phLength: 10 },
  { country: "Kenya", value: "254", code: "KE", phLength: 10 },
  { country: "Kiribati", value: "686", code: "KI", phLength: 8 },
  { country: "Kosovo", value: "383", code: "XK" },
  { country: "Kuwait", value: "965", code: "KW", phLength: 8 },
  { country: "Kyrgyzstan", value: "996", code: "KG" },
  { country: "Laos", value: "856", code: "LA" },
  { country: "Latvia", value: "371", code: "LV", phLength: 8 },
  { country: "Lebanon", value: "961", code: "LB", phLength: 7 },
  { country: "Lesotho", value: "266", code: "LS" },
  { country: "Liberia", value: "231", code: "LR", phLength: 7 },
  { country: "Libya", value: "218", code: "LY", phLength: 10 },
  { country: "Liechtenstein", value: "423", code: "LI" },
  { country: "Lithuania", value: "370", code: "LT", phLength: 8 },
  { country: "Luxembourg", value: "352", code: "LU", phLength: 9 },
  { country: "Macau", value: "853", code: "MO" },
  { country: "Macedonia", value: "389", code: "MK" },
  { country: "Madagascar", value: "261", code: "MG" },
  { country: "Malawi", value: "265", code: "MW" },
  { country: "Malaysia", value: "60", code: "MY", phLength: 7 },
  { country: "Maldives", value: "960", code: "MV", phLength: 7 },
  { country: "Mali", value: "223", code: "ML", phLength: 8 },
  { country: "Malta", value: "356", code: "MT", phLength: 8 },
  { country: "Marshall Islands", value: "692", code: "MH", phLength: 7 },
  { country: "Mauritania", value: "222", code: "MR" },
  { country: "Mauritius", value: "230", code: "MU", phLength: 8 },
  { country: "Mayotte", value: "262", code: "YT" },
  { country: "Mexico", value: "52", code: "MX", phLength: 10 },
  { country: "Micronesia", value: "691", code: "FM", phLength: 7 },
  { country: "Moldova", value: "373", code: "MD", phLength: 8 },
  { country: "Monaco", value: "377", code: "MC" },
  { country: "Mongolia", value: "976", code: "MN" },
  { country: "Montenegro", value: "382", code: "ME", phLength: 8 },
  { country: "Montserrat", value: "1-664", code: "MS", phLength: 10 },
  { country: "Morocco", value: "212", code: "MA" },
  { country: "Mozambique", value: "258", code: "MZ", phLength: 12 },
  { country: "Myanmar", value: "95", code: "MM", phLength: 8 },
  { country: "Namibia", value: "264", code: "NA" },
  { country: "Nauru", value: "674", code: "NR" },
  { country: "Nepal", value: "977", code: "NP", phLength: 10 },
  { country: "Netherlands", value: "31", code: "NL", phLength: 9 },
  { country: "Netherlands Antilles", value: "599", code: "AN" },
  { country: "New Caledonia", value: "687", code: "NC", phLength: 6 },
  { country: "New Zealand", value: "64", code: "NZ", phLength: 9 },
  { country: "Nicaragua", value: "505", code: "NI", phLength: 8 },
  { country: "Niger", value: "227", code: "NE", phLength: 8 },
  { country: "Nigeria", value: "234", code: "NG", phLength: 8 },
  { country: "Niue", value: "683", code: "NU", phLength: 4 },
  { country: "North Korea", value: "850", code: "KP" },
  {
    country: "Northern Mariana Islands",
    value: "1-670",
    code: "MP",
    phLength: 10,
  },
  { country: "Norway", value: "47", code: "NO", phLength: 8 },
  { country: "Oman", value: "968", code: "OM", phLength: 8 },
  { country: "Pakistan", value: "92", code: "PK", phLength: 10 },
  { country: "Palau", value: "680", code: "PW", phLength: 7 },
  { country: "Palestine", value: "970", code: "PS" },
  { country: "Panama", value: "507", code: "PA", phLength: 8 },
  { country: "Papua New Guinea", value: "675", code: "PG" },
  { country: "Paraguay", value: "595", code: "PY", phLength: 9 },
  { country: "Peru", value: "51", code: "PE", phLength: 9 },
  { country: "Philippines", value: "63", code: "PH", phLength: 10 },
  { country: "Pitcairn", value: "64", code: "PN" },
  { country: "Poland", value: "48", code: "PL", phLength: 9 },
  { country: "Portugal", value: "351", code: "PT", phLength: 9 },
  { country: "Puerto Rico (1-787)", value: "1-787", code: "PR" },
  { country: "Puerto Rico (1-939)", value: "1-939", code: "PR" },
  { country: "Qatar", value: "974", code: "QA", phLength: 8 },
  { country: "Republic of the Congo", value: "242", code: "CG" },
  { country: "Reunion", value: "262", code: "RE" },
  { country: "Romania", value: "40", code: "RO", phLength: 10 },
  { country: "Russia", value: "7", code: "RU", phLength: 10 },
  { country: "Rwanda", value: "250", code: "RW" },
  { country: "Saint Barthelemy", value: "590", code: "BL" },
  { country: "Saint Helena", value: "290", code: "SH" },
  {
    country: "Saint Kitts and Nevis",
    value: "1-869",
    code: "KN",
    phLength: 10,
  },
  { country: "Saint Lucia", value: "1-758", code: "LC", phLength: 10 },
  { country: "Saint Martin", value: "590", code: "MF" },
  { country: "Saint Pierre and Miquelon", value: "508", code: "PM" },
  {
    country: "Saint Vincent and the Grenadines",
    value: "1-784",
    code: "VC",
    phLength: 10,
  },
  { country: "Samoa", value: "685", code: "WS", phLength: 5 },
  { country: "San Marino", value: "378", code: "SM" },
  { country: "Sao Tome and Principe", value: "239", code: "ST" },
  { country: "Saudi Arabia", value: "966", code: "SA", phLength: 9 },
  { country: "Senegal", value: "221", code: "SN" },
  { country: "Serbia", value: "381", code: "RS", phLength: 8 },
  { country: "Seychelles", value: "248", code: "SC" },
  { country: "Sierra Leone", value: "232", code: "SL" },
  { country: "Singapore", value: "65", code: "SG", phLength: 8 },
  { country: "Sint Maarten", value: "1-721", code: "SX", phLength: 10 },
  { country: "Slovakia", value: "421", code: "SK", phLength: 9 },
  { country: "Slovenia", value: "386", code: "SI" },
  { country: "Solomon Islands", value: "677", code: "SB", phLength: 7 },
  { country: "Somalia", value: "252", code: "SO", phLength: 8 },
  { country: "South Africa", value: "27", code: "ZA", phLength: 9 },
  { country: "South Korea", value: "82", code: "KR", phLength: 10 },
  { country: "South Sudan", value: "211", code: "SS" },
  { country: "Spain", value: "34", code: "ES", phLength: 9 },
  { country: "Sri Lanka", value: "94", code: "LK", phLength: 7 },
  { country: "Sudan", value: "249", code: "SD" },
  { country: "Suriname", value: "597", code: "SR" },
  { country: "Svalbard and Jan Mayen", value: "47", code: "SJ" },
  { country: "Swaziland", value: "268", code: "SZ" },
  { country: "Sweden", value: "46", code: "SE", phLength: 7 },
  { country: "Switzerland", value: "41", code: "CH", phLength: 9 },
  { country: "Syria", value: "963", code: "SY", phLength: 9 },
  { country: "Taiwan", value: "886", code: "TW", phLength: 9 },
  { country: "Tajikistan", value: "992", code: "TJ" },
  { country: "Tanzania", value: "255", code: "TZ", phLength: 6 },
  { country: "Thailand", value: "66", code: "TH", phLength: 9 },
  { country: "Togo", value: "228", code: "TG", phLength: 8 },
  { country: "Tokelau", value: "690", code: "TK" },
  { country: "Tonga", value: "676", code: "TO" },
  { country: "Trinidad and Tobago", value: "1-868", code: "TT", phLength: 10 },
  { country: "Tunisia", value: "216", code: "TN", phLength: 8 },
  { country: "Turkey", value: "90", code: "TR", phLength: 10 },
  { country: "Turkmenistan", value: "993", code: "TM" },
  {
    country: "Turks and Caicos Islands",
    value: "1-649",
    code: "TC",
    phLength: 10,
  },
  { country: "Tuvalu", value: "688", code: "TV" },
  { country: "U.S. Virgin Islands", value: "1-340", code: "VI" },
  { country: "Uganda", value: "256", code: "UG" },
  { country: "Ukraine", value: "380", code: "UA", phLength: 9 },
  { country: "United Arab Emirates", value: "971", code: "AE", phLength: 9 },
  { country: "United Kingdom", value: "44", code: "GB", phLength: 10 },
  { country: "United States", value: "1", code: "US", phLength: 10 },
  { country: "Uruguay", value: "598", code: "UY" },
  { country: "Uzbekistan", value: "998", code: "UZ" },
  { country: "Vanuatu", value: "678", code: "VU" },
  { country: "Vatican", value: "379", code: "VA" },
  { country: "Venezuela", value: "58", code: "VE", phLength: 7 },
  { country: "Vietnam", value: "84", code: "VN", phLength: 9 },
  { country: "Wallis and Futuna", value: "681", code: "WF" },
  { country: "Western Sahara", value: "212", code: "EH" },
  { country: "Yemen", value: "967", code: "YE", phLength: 9 },
  { country: "Zambia", value: "260", code: "ZM", phLength: 9 },
  { country: "Zimbabwe", value: "263", code: "ZW", phLength: 9 },
];
module.exports={callingCodes}

